config/routes.rb
Rails.application.routes.draw do

  github_authenticate(org: ENV['GITHUB_ORG_NAME']) do
    resources :projects do
      resources :environments
      resources :settings, except: [:index] do

        member do
          get 'versions/:value_id', :action => 'versions', as: 'versions'
          put 'versions/:value_id/:version_id', :action => 'versions_revert', as: 'versions_revert'
        end

      end
    end
  end

  get 'settings/:uuid',
    to: 'environments#list_setting_by_uuid',
    as: 'setting',
    :format => true,
    constraints: { format: 'json' }

  root 'projects#index'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :project
  has_many :values
  has_many :environments, through: :values

  accepts_nested_attributes_for :values

  validates :name, presence: true
  validates :project_id, presence: true
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy, :versions, :versions_revert]
  before_action :set_parent, only: [:new, :create]
  before_action :prefill_all_environments, only: [:edit, :show]

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
    @project.environments.each do |environment|
      @setting.values.build environment: environment
    end
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)
    @setting.project = @project

    respond_to do |format|
      if @setting.save
        format.html { redirect_to project_url(@project), notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      # byebug
      if @setting.update(setting_params)
        format.html { redirect_to [@project, @setting], notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@project), notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def versions
    @value = Value.find(params[:value_id])
    @versions = @value.versions.reverse
    @versions.pop
  end

  def versions_revert
    @value = Value.find(params[:value_id])
    version = @value.versions.find(params[:version_id])
    if version
      version.reify.save
      redirect_to versions_project_setting_path(@project, @value.setting, @value), notice: 'Reverted.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
      @project = @setting.project
    end

    def set_parent
      @project = Project.friendly.find(params[:project_id])
    end

    def prefill_all_environments
      @project.environments.each do |environment|
        unless @setting.environments.exists?(environment)
          @setting.values.build environment: environment
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:name,
        values_attributes: [:id, :environment_id, :data]
      )
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= form_for [@project, @setting], html: { class: "form-horizontal m-t-2", role: "form" } do |f|

  - if @setting.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @setting.errors.full_messages.each do |msg|
          %li= msg

  .form-group.row
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  %h3.m-b-2.m-t-3 Values:
  = f.fields_for :values do |builder|
    = builder.hidden_field :environment_id
    .form-group.row
      = builder.label :data, builder.object.environment.name, class: 'col-sm-2 control-label'
      .col-sm-10
        = builder.text_field :data, class: 'form-control'

  .form-group.row
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/settings/edit.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}
  = link_to project_setting_path(@project, @setting), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-info-sign
    Show

%h1.m-t-2 Editing setting

= render 'form'

app/views/settings/new.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}

%h1.m-t-2 New setting
= render 'form'

app/views/settings/show.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}
  = link_to edit_project_setting_path(@project, @setting), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-pencil
    Edit

%h1.m-t-2
  %code= @setting.name

.container
  %dl.dl-horizontal.m-t-2
    - @setting.values.each do |value|
      %dt.col-sm-2=  value.environment.name
      %dd.col-sm-10
        %code= value.data
        - if value.versions.size > 1
          %small= link_to "(versions: #{value.versions.size})", versions_project_setting_path(@project, value.setting, value)

app/views/settings/versions.html.haml
.btn-group
  = link_to project_setting_path(@project, @setting), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to
    %code= @setting.name

%h1.m-t-2 Versions history
%h3
  = @value.environment.name
  %span.glyphicon.glyphicon-chevron-right
  %code= @setting.name


.table-responsive.m-t-2
  %table.table.table-striped.table-bordered.table-hover.table-sm
    %thead
      %tr
        %th Version
        %th Date
        %th Value
        %th

    %tbody
      %tr
        %td Current
        %td= @value.updated_at
        %td
          %code= @value.data
        %td

      - @versions.each do |version|
        %tr
          %td= version.index
          %td= version.created_at
          %td
            %code=version.reify.data
          %td= link_to 'Revert', versions_revert_project_setting_path(@project, @value.setting, @value, version.id), :method => :put, :data => { :confirm => 'Are you sure?' }