config/routes.rb
Rails.application.routes.draw do

  github_authenticate(org: ENV['GITHUB_ORG_NAME']) do
    resources :projects do
      resources :environments
      resources :settings, except: [:index] do

        member do
          get 'versions/:value_id', :action => 'versions', as: 'versions'
          put 'versions/:value_id/:version_id', :action => 'versions_revert', as: 'versions_revert'
        end

      end
    end
  end

  get 'settings/:uuid',
    to: 'environments#list_setting_by_uuid',
    as: 'setting',
    :format => true,
    constraints: { format: 'json' }

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId

  has_many :environments
  has_many :settings

  friendly_id :name, use: :slugged
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, html: { class: "form-horizontal m-t-2", role: "form" } do |f|
  - if @project.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .form-group.row
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  .form-group.row
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/projects/edit.html.haml
.btn-group
  = link_to projects_path, class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @project, class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-info-sign
    Show

%h1.m-t-2 Editing project

= render 'form'

app/views/projects/index.html.haml
.btn-group
  = link_to new_project_path, class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-plus
    New project


%h1.m-t-2  Listing projects

.table-responsive.m-t-2
  %table.table.table-striped.table-bordered.table-hover.table-sm
    %thead
      %tr
        %th Name
        %th
        %th
        %th

    %tbody
      - @projects.each do |project|
        %tr
          %td= project.name
          %td= link_to 'Show', project
          %td= link_to 'Edit', edit_project_path(project)
          %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/projects/new.html.haml
.btn-group
  = link_to projects_path, class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Projects

%h1.m-t-2 New project

= render 'form'

app/views/projects/show.html.haml
.btn-group
  = link_to projects_path, class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Projects
  = link_to edit_project_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-pencil
    Edit
  = link_to project_environments_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-folder-open
    Environments
  = link_to new_project_environment_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-plus
    New environment

%h1.m-t-2= @project.name

.btn-group.m-t-2
  = link_to new_project_setting_path(@project), class: 'btn btn-primary btn-sm' do
    %span.glyphicon.glyphicon-plus
    New setting

.table-responsive.m-t-1
  %table.table.table-striped.table-bordered.table-hover.table-sm
    %thead
      %tr
        %th Name
        %th
        %th

    %tbody
      - @project.settings.each do |setting|
        %tr
          %td= link_to setting.name, [@project, setting]
          %td= link_to 'Edit', edit_project_setting_path(@project, setting)
          %td= link_to 'Destroy', [@project, setting], :method => :delete, :data => { :confirm => 'Are you sure?' }