config/routes.rb
Rails.application.routes.draw do

  github_authenticate(org: ENV['GITHUB_ORG_NAME']) do
    resources :projects do
      resources :environments
      resources :settings, except: [:index] do

        member do
          get 'versions/:value_id', :action => 'versions', as: 'versions'
          put 'versions/:value_id/:version_id', :action => 'versions_revert', as: 'versions_revert'
        end

      end
    end
  end

  get 'settings/:uuid',
    to: 'environments#list_setting_by_uuid',
    as: 'setting',
    :format => true,
    constraints: { format: 'json' }

  root 'projects#index'

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  belongs_to :project
  has_many :values
  has_many :settings, through: :values

  validates :project_id, presence: true
  validates :name, presence: true

  before_create do
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]
  before_action :set_parent, only: [:index, :new, :create]

  # GET /environments
  # GET /environments.json
  def index
    @environments = @project.environments.all
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)
    @environment.project = @project

    respond_to do |format|
      if @environment.save
        format.html { redirect_to project_url(@project), notice: 'Environment was successfully created.' }
        format.json { render :show, status: :created, location: @environment }
      else
        format.html { render :new }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      if @environment.update(environment_params)
        format.html { redirect_to [@project, @environment], notice: 'Environment was successfully updated.' }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :edit }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment.destroy
    respond_to do |format|
      format.html { redirect_to project_environments_url(@project.id), notice: 'Environment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET settings/:uuid
  def list_setting_by_uuid
    environment = Environment.find_by_uuid(params[:uuid])
    @values = environment.values
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
      @project = @environment.project
    end

    def set_parent
      @project = Project.friendly.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:name)
    end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.haml
= form_for [@project, @environment], html: { class: "form-horizontal m-t-2", role: "form" } do |f|
  - if @environment.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@environment.errors.count, "error")} prohibited this environment from being saved:"
      %ul
        - @environment.errors.full_messages.each do |msg|
          %li= msg

  .form-group.row
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  .form-group.row
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/environments/edit.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}
  = link_to project_environments_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-folder-open
    Environments
  = link_to project_environment_path(@project, @environment), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-info-sign
    Show

%h1.m-t-2 Editing project

= render 'form'

app/views/environments/index.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}
  = link_to new_project_environment_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-plus
    New environment


%h1.m-t-2  Listing environments

.table-responsive.m-t-2
  %table.table.table-striped.table-bordered.table-hover.table-sm
    %thead
      %tr
        %th Name
        %th UUID
        %th
        %th
        %th
        %th

    %tbody
      - @environments.each do |environment|
        %tr
          %td= environment.name
          %td
            %code= environment.uuid
          %td= link_to 'List settings', setting_path(environment.uuid, :format => 'json')
          %td= link_to 'Show', [@project, environment]
          %td= link_to 'Edit', edit_project_environment_path(@project, environment)
          %td= link_to 'Destroy', [@project, environment], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/environments/new.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}
  = link_to project_environments_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-folder-open
    Environments

%h1.m-t-2 New environment

= render 'form'

app/views/environments/show.html.haml
.btn-group
  = link_to project_path(@project), class: :'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-list-alt
    Back to #{@project.name}
  = link_to project_environments_path(@project), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-folder-open
    Environments
  = link_to edit_project_environment_path(@project, @environment), class: 'btn btn-secondary btn-sm' do
    %span.glyphicon.glyphicon-pencil
    Edit

%h1.m-t-2  Show environment


.container
  %dl.dl-horizontal.m-t-2
    %dt.col-sm-1   Name:
    %dd.col-sm-11= @environment.name

    %dt.col-sm-1   UUID:
    %dd.col-sm-11= @environment.uuid